
name: POWERMODE Auto Scan

on:

  schedule:

    - cron: "0 8 * * *"

    - cron: "0 15 * * *"

  workflow_dispatch:

jobs:

  run-powermode:

    runs-on: ubuntu-latest

    steps:

      - name: Send start message

        run: curl -s -X POST "https://api.telegram.org/bot8682008294:AAG2ssNDJKPy3dYEkoqg5EHKWz2quyNdcZ0/sendMessage" --data-urlencode "chat_id=6375369326" --data-urlencode "text=POWERMODE starter scan 🚀"

      - name: Checkout repo

        uses: actions/checkout@v4

      - name: Set up Python

        uses: actions/setup-python@v5

        with:

          python-version: "3.11"

      - name: Install packages

        run: |

          pip install yfinance pandas numpy openpyxl pandas_ta ta

      - name: Run Oslo V7.1

        run: python POWERMODE_OSLO_V71_FULL_CELL.py

      - name: Run Oslo V4.2

        run: python POWERMODE_V42_FULL_CELL.py

      - name: Run Sverige V8.1

        run: python POWERMODE_SVERIGE_V81_KORRIGERT.py

      - name: Run Master

        run: python POWERMODE_MASTER_CELL.py

      - name: Send finished message

        if: success()

        run: curl -s -X POST "https://api.telegram.org/bot8682008294:AAG2ssNDJKPy3dYEkoqg5EHKWz2quyNdcZ0/sendMessage" --data-urlencode "chat_id=6375369326" --data-urlencode "text=POWERMODE ferdig ✅"

      - name: Send failed message

        if: failure()

        run: curl -s -X POST "https://api.telegram.org/bot8682008294:AAG2ssNDJKPy3dYEkoqg5EHKWz2quyNdcZ0/sendMessage" --data-urlencode "chat_id=6375369326" --data-urlencode "text=POWERMODE feilet ❌ Åpne GitHub Actions og sjekk feilmelding."
